### ISSUE TITLE
docker run fails. 

### ISSUE THREAD

**Issue by erume2020** [sapcc/vrops-exporter#122]
docker run of vrops exporter errors. ( see below )

# docker run -it hub.global.cloud.sap/monsoon/vrops_exporter /bin/sh
Unable to find image ‘hub.global.cloud.sap/monsoon/vrops_exporter:latest’ locally
docker: Error response from daemon: Get https://hub.global.cloud.sap/v2/: dial tcp 10.46.2.200:443: connect: no route to host.

Any leads on whats going on ?

**Comment by viennaa** [comment]
You need to run `make` to build the image first. Given repository is internal and therefore a straight pull won't work.

Got to adjust documentation here. Thanks for the hint.
