### ISSUE TITLE
Will this work with VMware Horizon?

### ISSUE THREAD

**Issue by Mooihoek** [sapcc/vrops-exporter#161]
Sorry not an issue, but a question. Would the exporter but able to pick up metrics from https://docs.vmware.com/en/Management-Packs-for-vRealize-Operations-Manager/1.1/rn/Horizon-11-Release-Notes.html ?

**Comment by richardtief** [comment]
This is quite possible, but not yet foreseen. Also depends on the API design that VMware hands out to their products. If it remains standardised, then it will also work with it in the future.
