### ISSUE TITLE
Collecting stats from UserDesktop resource?

### ISSUE THREAD

**Issue by proffalken** [sapcc/vrops-exporter#180]
Hello,

Thanks for a great project.

We're in the process of setting this up and I'm struggling to get back the UserDesktop stats, specifically the ones around PCoIP.

Ideally I'm after the `pcoip|round_trip_latency` metric, however if I can grab all of the metrics that are under the `UserDesktop` namespace that would be great.

I seem to already have access to most, it's just the PCoIP ones that seem to be missing at the moment - what do I need to do in order to retrieve them?

**Comment by viennaa** [comment]
@proffalken sorry for not getting back to you earlier.

Do you still have the problem? Can you point out, where to find your requested metric exactly? Please take it from the [current vmware documentation](https://docs.vmware.com/en/vRealize-Operations-Manager/8.4/com.vmware.vcom.metrics.doc/GUID-9DB18E49-5E00-4534-B5FF-6276948D5A09.html)

**Comment by proffalken** [comment]
@viennaa - The metrics come from a V4V plugin and are not documented in the current VMWare documentation.

We ended up writing additional `get_adapter` functions to talk directly to the V4V API running one request for every VM discovered.

We've got a ticket on our backlog to upstream it at some point in the future, however there's a lot of client-specific code in there so it may take a good while to achieve.

**Comment by viennaa** [comment]
Ok, problem is you will not be benefiting from the latest updates we are making. If have an idea how to bring this upstream, feel free to open a PR for discussion.

I just opened #188 to make it a little bit more generic too, but ofc it is hard to tell what other ppl need without knowing.
