### ISSUE TITLE
Inventory can only handle one vCenter at a time

### ISSUE THREAD

**Issue by jeoffzheng** [sapcc/vrops-exporter#204]
hi, Team

i am running a issue with the exporter.. i would like seek your help here.
[Issue description]
I have a vrops with multiple vcenters , however, when every query against that inventory url with vcenters, it  always replies with a different vcenter, not all of them. how can the exporter query all the vcenters ?

i attached the test output here. FYI.   
[update-consolidate.log](https://github.com/sapcc/vrops-exporter/files/8283360/update-consolidate.log)

pls help on this issue. thanks.

thanks
Jeoff

**Comment by jbroquard** [comment]
Does the latest version have support for multiple vcenters now?

**Comment by richardtief** [comment]
Yes, sure. This was implemented with #211.
