### ISSUE TITLE
Usage of exporter.

### ISSUE THREAD

**Issue by daulet-ertaev** [sapcc/vrops-exporter#228]
I have tried to run both of inventory and exporter. It seems like the inventory ran correctly cause i can get some info from localhost:80/vrops_list ... etc. But after running exporter.py with appropriate options I cant get metrics. Maybe I incorrectly understood how your exporter works. I try to get the metrics by localhost:9000/metrics as well as in your code runs prometheus server. If it doesnt works in that way, could you correct me?  Or are there some issues with running your project?
![Безымянный](https://user-images.githubusercontent.com/65158013/176668340-65b16330-93ae-462f-839b-8cede04721c1.png)
P.S in the screenshot we can see that collectors working properly. Then I have some error with nsxt adapter
![Безымянный](https://user-images.githubusercontent.com/65158013/176668626-2693d938-18ca-4b6c-b38a-539d50cd9520.png)
P.S when I try to go localhost:9000 i can see these messages from exporter(i hope:))

**Comment by richardtief** [comment]
That looks good to me. But I found the problem you encountered. The vcops adapter doesn't seem to be present in your environment, so the inventory is stuck and there is no initial iteration. This is why the exporter is complaining with the message shown. I have provided a solution, you can simply make the change in your code to test it.
