### ISSUE TITLE
keppel.eu-de-1.cloud.sap appears to be down? 

### ISSUE THREAD

**Issue by asavagebny** [sapcc/vrops-exporter#243]
Hello... I'm trying to run the make on the dockerfile and am getting the following error.. 

it would appear that keppel.eu-de-1.cloud.sap  is not resolvable anymore? 

Get "https://keppel.eu-de-1.cloud.sap/v2/": dial tcp: lookup keppel.eu-de-1.cloud.sap on mydnsserver:53: server misbehaving
make: *** [Makefile:12: build] Error 1

Thank you,
Adam

**Comment by asavagebny** [comment]
Annnybody?

**Comment by viennaa** [comment]
keppel is our internal registry url. You might need to swap it with something from upstream. You should be able to pull in another registry providing an alpine image.

If you are using docker, replacing the whole `FROM keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/library/alpine:latest` to something along
`FROM alpine:latest` should do the trick. [1]

[1] https://hub.docker.com/_/alpine/
