### ISSUE TITLE
Expose custom tag information

### ISSUE THREAD

**Issue by richardtief** [sapcc/vrops-exporter#259]
We have custom tags for VMware objects that allow mapping to e.g. OpenStack. If possible, these should be exposed as a own metric or added as a label on the resource metrics to be able to filter by. 

- [ ] check if the data is available in the vrops API.
- [ ] implement
- [ ] test and verify

**Comment by kevin-fischer** [comment]
Duplicate: --> https://github.com/sapcc/helm-charts/pull/5028

**Comment by richardtief** [comment]
Perfect! Didn't expect that the tags could be exported as a property. Good to see that our structure covers such specifics.
